NorrathIQ_BundledPack = {
    meta = {
        id = "p99-seed-2026-08-10",
        schemaVersion = 1,
        version = "1.0.0-seed",
        generatedAt = "2026-08-10T00:00:00Z",
        source = "Project 1999 Wiki",
        disclaimer = "Community-maintained data; verify uncertain facts.",
    },
    entities = {
        ["item:gnoll-fang"] = {
            id = "item:gnoll-fang", type = "item", name = "Gnoll Fang",
            aliases = { "a gnoll fang" }, classification = "Quest Item", flags = { Q = true },
            summary = "A low-level Qeynos quest turn-in taken from gnolls.",
            uses = { "Moonstones Quest: turn in to Captain Tillin for a Moonstone." },
            drops = {
                { npc = "Gnolls", zone = "Blackburrow", level = "approximately 2-15", confidence = "high" },
                { npc = "Gnolls", zone = "Qeynos Hills", level = "approximately 2-10", confidence = "medium" },
            },
            quests = { "quest:moonstones" }, turnins = { "npc:captain-tillin" },
            recommendation = { action = "KEEP", reason = "Known repeatable quest turn-in with useful experience and faction." },
            source = { url = "https://wiki.project1999.com/Moonstones_Quest", revision = "seed", confidence = "high" },
        },
        ["item:moonstone"] = {
            id = "item:moonstone", type = "item", name = "Moonstone", classification = "Quest Item", flags = { Q = true },
            summary = "Received from Captain Tillin and optionally turned in to McNeal Jocub.",
            uses = { "Moonstones Quest: exchange with McNeal Jocub for Black Burrow Stout." },
            quests = { "quest:moonstones" }, turnins = { "npc:mcneal-jocub" },
            recommendation = { action = "KEEP", reason = "Keep if continuing the Moonstones quest; otherwise it is optional." },
            source = { url = "https://wiki.project1999.com/Moonstones_Quest", revision = "seed", confidence = "high" },
        },
        ["item:tasarin-375-left"] = {
            id = "item:tasarin-375-left", type = "item", name = "Part of Tasarin's Grimoire Pg. 375 (Left)",
            aliases = { "Part of Tasarin's Grimoire Pg.375 (Left)" }, classification = "Enchanter Research Component", flags = { R = true, T = true },
            summary = "One half of an Enchanter spell-research page.",
            uses = { "Spell Research: Endure Magic (trivial 42)." }, recipes = { "recipe:endure-magic" },
            related = { "item:tasarin-375-right" },
            recommendation = { action = "KEEP", reason = "Keep when researching Endure Magic; otherwise low priority." },
            source = { url = "https://wiki.project1999.com/Skill_Research", revision = "seed", confidence = "high" },
        },
        ["item:tasarin-375-right"] = {
            id = "item:tasarin-375-right", type = "item", name = "Part of Tasarin's Grimoire Pg. 375 (Right)",
            aliases = { "Part of Tasarin's Grimoire Pg.375 (Right)" }, classification = "Enchanter Research Component", flags = { R = true, T = true },
            summary = "One half of an Enchanter spell-research page.",
            uses = { "Spell Research: Endure Magic (trivial 42)." }, recipes = { "recipe:endure-magic" },
            related = { "item:tasarin-375-left" },
            drops = { { npc = "Several level-appropriate mobs", zone = "Multiple classic zones", level = "roughly 15-25", confidence = "medium" } },
            recommendation = { action = "KEEP", reason = "Keep when researching Endure Magic; otherwise low priority." },
            source = { url = "https://wiki.project1999.com/Part_of_Tasarin%27s_Grimoire_Pg._375_%28Right%29", revision = "381883", confidence = "high" },
        },
        ["item:top-broken-staff"] = {
            id = "item:top-broken-staff", type = "item", name = "Top of Broken Staff", classification = "Quest Chain Item", flags = { Q = true, K = true },
            summary = "A rare staff piece carried by a gnoll hunter in Qeynos Hills.",
            drops = { { npc = "a gnoll hunter", zone = "Qeynos Hills", level = "approximately 6-8", confidence = "high", marker = "spawn:gnoll-hunter" } },
            related = { "item:bottom-broken-staff" },
            recommendation = { action = "KEEP", reason = "Rare quest-chain component with a matching staff half." },
            source = { url = "https://wiki.project1999.com/A_Gnoll_Hunter", revision = "seed", confidence = "high" },
        },
        ["item:bottom-broken-staff"] = {
            id = "item:bottom-broken-staff", type = "item", name = "Bottom of Broken Staff", classification = "Quest Chain Item", flags = { Q = true, K = true },
            summary = "The companion piece to the Top of Broken Staff.", related = { "item:top-broken-staff" },
            recommendation = { action = "KEEP", reason = "Rare quest-chain component with a matching staff half." },
            source = { url = "https://wiki.project1999.com/A_Gnoll_Hunter", revision = "seed", confidence = "high" },
        },
        ["item:rough-elm-recurve-bow"] = {
            id = "item:rough-elm-recurve-bow", type = "item", name = "Rough Elm Recurve Bow",
            aliases = { "Rough Elm Recurve Bow (Hemp)", "Rough Elm Recurve Bow (Linen)", "Rough Elm Recurve Bow (Silk)" },
            classification = "Ranged Weapon", flags = { Q = true, T = true }, slot = "RANGED",
            classes = { "Warrior", "Paladin", "Ranger", "Shadow Knight", "Rogue" },
            stats = { damage = "11-13", delay = "43-51", range = 75, weight = 4.0 },
            summary = "A quest reward and player-crafted fletching bow with string-dependent variants.",
            uses = { "Reward from Poacher's Head Quest (Surefall Glade).", "Crafted with Fletching (trivial 68)." },
            recipes = { "recipe:rough-elm-bow" }, quests = { "quest:poachers-head" },
            recommendation = { action = "REVIEW", reason = "Compare the exact realm variant with your equipped ranged weapon." },
            source = { url = "https://wiki.project1999.com/Rough_Elm_Recurve_Bow", revision = "168296", confidence = "high" },
        },
        ["quest:moonstones"] = {
            id = "quest:moonstones", type = "quest", name = "Moonstones Quest", aliases = { "Moonstones" },
            classification = "Repeatable Quest", level = "4+", zone = "South Qeynos",
            summary = "Collect Gnoll Fangs, turn them in to Captain Tillin, then optionally exchange Moonstones with McNeal Jocub.",
            objectives = { "Loot Gnoll Fangs from gnolls.", "Turn Gnoll Fangs in to Captain Tillin.", "Optionally turn Moonstones in to McNeal Jocub." },
            related = { "item:gnoll-fang", "item:moonstone", "npc:captain-tillin", "npc:mcneal-jocub" },
            source = { url = "https://wiki.project1999.com/Moonstones_Quest", revision = "seed", confidence = "high" },
        },
        ["quest:poachers-head"] = {
            id = "quest:poachers-head", type = "quest", name = "Poacher's Head Quest (Surefall Glade)", aliases = { "Poacher's Head Quest" },
            classification = "Quest", level = "5+", zone = "Surefall Glade",
            summary = "A Surefall Glade quest associated with poachers and the Rough Elm Recurve Bow reward.",
            related = { "item:rough-elm-recurve-bow", "npc:gillarian-naelev" },
            source = { url = "https://wiki.project1999.com/Poacher%27s_Head_Quest_%28Surefall_Glade%29", revision = "seed", confidence = "high" },
        },
        ["recipe:endure-magic"] = {
            id = "recipe:endure-magic", type = "recipe", name = "Endure Magic Research", classification = "Spell Research",
            skill = "Spell Research", trivial = 42, result = "Endure Magic",
            components = { "item:tasarin-375-left", "item:tasarin-375-right" },
            summary = "Combine the left and right halves of Tasarin's Grimoire page 375.",
            source = { url = "https://wiki.project1999.com/Skill_Research", revision = "seed", confidence = "high" },
        },
        ["recipe:rough-elm-bow"] = {
            id = "recipe:rough-elm-bow", type = "recipe", name = "Rough Elm Recurve Bow", classification = "Fletching Recipe",
            skill = "Fletching", trivial = 68, result = "Rough Elm Recurve Bow",
            componentsText = { "1 x Elm Bow Staff", "1 x Hemp, Linen, or Silk string/twine (variant-dependent)" },
            summary = "Fletching combine whose string determines damage and delay.",
            source = { url = "https://wiki.project1999.com/Rough_Elm_Recurve_Bow", revision = "168296", confidence = "high" },
        },
        ["npc:captain-tillin"] = {
            id = "npc:captain-tillin", type = "npc", name = "Captain Tillin", classification = "Quest Turn-in NPC",
            zone = "South Qeynos", level = "Guard", location = "Warrior arena, upper level", map = { zone = "South Qeynos", x = 0.55, y = 0.33, confidence = "approximate" },
            summary = "Accepts Gnoll Fangs and returns Moonstones.", related = { "quest:moonstones", "item:gnoll-fang" },
            source = { url = "https://wiki.project1999.com/Moonstones_Quest", revision = "seed", confidence = "high" },
        },
        ["npc:mcneal-jocub"] = {
            id = "npc:mcneal-jocub", type = "npc", name = "McNeal Jocub", classification = "Quest NPC",
            zone = "South Qeynos", location = "Fish's Ale", map = { zone = "South Qeynos", x = 0.31, y = 0.66, confidence = "approximate" },
            summary = "Optionally accepts Moonstones for Black Burrow Stout.", related = { "quest:moonstones", "item:moonstone" },
            source = { url = "https://wiki.project1999.com/Moonstones_Quest", revision = "seed", confidence = "high" },
        },
        ["npc:gnoll-hunter"] = {
            id = "npc:gnoll-hunter", type = "npc", name = "a gnoll hunter", classification = "Rare NPC",
            zone = "Qeynos Hills", level = "approximately 6-8", map = { zone = "Qeynos Hills", x = 0.48, y = 0.69, confidence = "approximate" },
            summary = "A rare spawn with a route toward the undead ruins and back to Blackburrow.",
            related = { "item:top-broken-staff", "item:bottom-broken-staff" },
            source = { url = "https://wiki.project1999.com/A_Gnoll_Hunter", revision = "seed", confidence = "high" },
        },
        ["npc:gillarian-naelev"] = {
            id = "npc:gillarian-naelev", type = "npc", name = "Gillarian Naelev", classification = "Quest Giver",
            zone = "Surefall Glade", level = "61", map = { zone = "Surefall Glade", x = 0.56, y = 0.48, confidence = "approximate" },
            summary = "Quest NPC for the Surefall Glade Poacher's Head Quest.", related = { "quest:poachers-head" },
            source = { url = "https://wiki.project1999.com/Gillarian_Naelev", revision = "189286", confidence = "high" },
        },
        ["zone:blackburrow"] = {
            id = "zone:blackburrow", type = "zone", name = "Blackburrow", classification = "Dungeon", level = "roughly 5-15",
            summary = "Gnoll dungeon connected to Qeynos Hills and a primary source of Gnoll Fangs.",
            source = { url = "https://wiki.project1999.com/Blackburrow", revision = "seed", confidence = "medium" },
        },
        ["zone:qeynos-hills"] = {
            id = "zone:qeynos-hills", type = "zone", name = "Qeynos Hills", classification = "Outdoor Zone",
            summary = "Outdoor region between Qeynos, Surefall Glade, Blackburrow, and the Karanas.",
            source = { url = "https://wiki.project1999.com/Qeynos_Hills", revision = "seed", confidence = "medium" },
        },
        ["spell:endure-magic"] = {
            id = "spell:endure-magic", type = "spell", name = "Endure Magic", classification = "Enchanter Spell",
            game = "eq", system = "EverQuest",
            level = "20", summary = "An Enchanter spell produced through page-375 spell research.", related = { "recipe:endure-magic" },
            source = { url = "https://wiki.project1999.com/Skill_Research", revision = "seed", confidence = "high" },
        },
    },
    spawns = {
        ["spawn:gnoll-hunter"] = {
            id = "spawn:gnoll-hunter", zone = "Qeynos Hills", x = 0.48, y = 0.69,
            label = "a gnoll hunter (approximate route)", confidence = "approximate",
            path = { { 0.48, 0.69 }, { 0.45, 0.58 }, { 0.47, 0.48 }, { 0.51, 0.40 } },
        },
    },
    zones = {
        ["South Qeynos"] = { note = "Generated coordinate grid; exact realm calibration not installed." },
        ["Qeynos Hills"] = { note = "Generated coordinate grid; the gnoll hunter route is approximate." },
        ["Blackburrow"] = { note = "Known source zone; no trustworthy exact pin is available in the seed pack." },
        ["Surefall Glade"] = { note = "Generated coordinate grid; exact realm calibration not installed." },
    },
}
